local builtin = require('telescope.builtin')

vim.keymap.set('n', '<leader>bb', builtin.buffers, { desc = 'Find buffers' })
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = 'Find files' })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, { desc = 'Live grep' })
vim.keymap.set('n', '<leader>fs', builtin.grep_string, { desc = 'Grep string' })
vim.keymap.set('n', '<leader>pf', function()
	builtin.grep_string({ search = vim.fn.input("> ") })
end, { desc = 'Grep string (input)' })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = 'Help tags' })
vim.keymap.set('n', '<leader>fr', builtin.oldfiles, { desc = 'Recent files' })
vim.keymap.set('n', '<leader>gf', builtin.git_files, { desc = 'Git files' })
vim.keymap.set('n', '<leader>mp', builtin.man_pages, { desc = 'Man pages' })
vim.keymap.set('n', '<leader>vc', builtin.colorscheme, { desc = 'Colorschemes' })
vim.keymap.set('n', '<leader>vx', builtin.commands, { desc = 'Commands' })
vim.keymap.set('n', '<leader>kb', function()
	builtin.keymaps({ show_plug = false })
end, { desc = 'Keymaps' })
