;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================
include-file = colors.ini

[bar/example]
monitor = ${env:MONITOR:eDP1}
width = 100%
height = 20pt
radius = 0

; dpi = 96

background = ${colors.background-alt}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0
border-color = #00000000

padding-left = 0
padding-right = 0

module-margin = 0

font-0 = Terminus;
font-1 = Symbols Nerd Font:size=11;1

modules-left = i3 xwindow
modules-right = xkeyboard wlan battery pulseaudio date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
wm-restack = i3

; override-redirect = true

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/i3]
type = internal/i3
pin-workspaces = true
strip-wsnumbers = true

format = <label-state><label-mode>
format-background = ${colors.background}

label-mode = %mode%
label-mode-padding = 2
label-mode-background = ${colors.background}

label-focused = %index%
label-focused-foreground = ${colors.selected}
label-focused-background = ${colors.background}
label-focused-padding = 2

label-unfocused = %index%
label-unfocused-background = ${colors.background}
label-unfocused-padding = 2

label-visible = %index%
label-visible-background = ${colors.background}
label-visible-padding = 2

label-urgent = %index%
label-urgent-foreground = ${colors.background}
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

[module/xwindow]
type = internal/xwindow
format = <label>
format-background = ${colors.background-alt}
format-foreground = ${colors.foreground}
format-padding = 2
label = %title:0:100:...%

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
; Default: 100
full-at = 100

low-at = 10

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = AC

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 5

time-format = %H:%M
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>
format-low = <label-low> <animation-low>

format-charging-background = ${colors.background}
format-discharging-background = ${colors.background}
format-full-background = ${colors.background}
format-low-background = ${colors.background}

format-charging-padding = 4
format-discharging-padding = 4
format-full-padding = 4
format-low-padding = 4

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = %percentage%%
label-low = %percentage%%

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${colors.primary}

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${colors.primary}
animation-charging-framerate = 750

animation-low-0 = !
animation-low-1 = 
animation-low-foreground = ${colors.alert}
animation-low-framerate = 200

[module/pulseaudio]
type = internal/pulseaudio

format-padding = 4
format-volume-prefix-foreground = ${colors.primary}
format-volume = <ramp-volume> <label-volume>
format-volume-background = ${colors.background}

label-volume = %percentage:2%%

label-muted = muted
label-muted-foreground = ${colors.disabled}
label-muted-background = ${colors.background}

; Only applies if <ramp-volume> is used
ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰕾
ramp-volume-foreground = ${colors.primary}

; Right and Middle click
click-right = pavucontrol

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
format-padding = 3
format-background = ${colors.background}

label-layout = %layout%
label-layout-foreground = ${colors.disabled}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[network-base]
type = internal/network
interval = 5
format-padding = 4
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %ifname% disconnected
label-disconnected-foreground = ${colors.disabled}

format-connected-background = ${colors.background}
format-disconnected-background = ${colors.background}

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = 󰖩 
label-connected-foreground = ${colors.secondary}

[module/date]
type = internal/date
interval = 1

format-background = ${colors.background}

date = %a, %b %d %R
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.foreground}
label-background = ${colors.background}
label-padding = 4

[module/sep]
type = custom/text
format = <label>
format-background = ${colors.background-alt}
format-padding = 2
label = " "

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
